language: node_js
node_js:
  - "6"
git:
  depth: 1
script:
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  project_name: freeCodeCamp-FrontEnd-Projects
  on:
    branch: master
